### ISSUE TITLE
Failing Test

### ISSUE THREAD

**Issue by w3aran** [rollup/rollup-starter-project#15]
**Command:**

`npm test`

**Result:**
```
npm test

> rollup-starter-project@1.0.0 pretest /Users/developer/git/demo/rollup-starter-project
> npm run build


> rollup-starter-project@1.0.0 prebuild /Users/developer/git/demo/rollup-starter-project
> eslint lib test


> rollup-starter-project@1.0.0 build /Users/developer/git/demo/rollup-starter-project
> rollup -c

Error loading /Users/developer/git/demo/rollup-starter-project/lib/index.js: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
Error: Error loading /Users/developer/git/demo/rollup-starter-project/lib/index.js: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
    at preflightCheck (/Users/developer/git/demo/rollup-starter-project/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:43:102)
    at transform$1 (/Users/developer/git/demo/rollup-starter-project/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:104:18)
    at /Users/developer/git/demo/rollup-starter-project/node_modules/rollup/src/utils/transform.js:9:28
    at process._tickCallback (node.js:406:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:141:18)
    at node.js:933:3
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
....
```

**Comment by yakanet** [comment]
Seems there is a breaking change in the babel-preset-es2015 plugin from the version 6.13.1.
To fix that, in your package.json, you need to use the exact version 6.9.0.

 -"babel-preset-es2015": "^6.9.0",
+"babel-preset-es2015": "6.9.0",

**Comment by eventualbuddha** [comment]
Fixed by https://github.com/rollup/rollup-starter-project/commit/c53d016f9d04a4edbb6c5b552f24ded189327ff4.
